#ifndef ANSICODES_H
#define ANSICODES_H

#define ANSI_ESC_RESET     "\x1b[0m"
#define ANSI_ESC_BOLD      "\x1b[1m"
#define ANSI_ESC_FAINT     "\x1b[2m"
#define ANSI_ESC_ITALIC    "\x1b[3m"
#define ANSI_ESC_ULINE     "\x1b[4m"
#define ANSI_ESC_SBLINK    "\x1b[5m"
#define ANSI_ESC_RBLINK    "\x1b[6m"
#define ANSI_ESC_IMGNEG    "\x1b[7m"
#define ANSI_ESC_CONCEAL   "\x1b[8m"
#define ANSI_ESC_CROSS     "\x1b[9m"
#define ANSI_ESC_DFTFONT   "\x1b[10m"
#define ANSI_ESC_1AFONT    "\x1b[11m"
#define ANSI_ESC_2AFONT    "\x1b[12m"
#define ANSI_ESC_3AFONT    "\x1b[13m"
#define ANSI_ESC_4AFONT    "\x1b[14m"
#define ANSI_ESC_5AFONT    "\x1b[15m"
#define ANSI_ESC_6AFONT    "\x1b[16m"
#define ANSI_ESC_7AFONT    "\x1b[17m"
#define ANSI_ESC_8AFONT    "\x1b[18m"
#define ANSI_ESC_9AFONT    "\x1b[19m"
#define ANSI_ESC_FRACT     "\x1b[20m"
#define ANSI_ESC_BOFFUDB   "\x1b[21m"
#define ANSI_ESC_NORMC     "\x1b[22m"
#define ANSI_ESC_NITNFRA   "\x1b[23m"
#define ANSI_ESC_NUNDERL   "\x1b[24m"
#define ANSI_ESC_NBLINK    "\x1b[25m"
#define ANSI_ESC_RESERVED1 "\x1b[26m"
#define ANSI_ESC_IMGPOS    "\x1b[27m"
#define ANSI_ESC_REVEAL    "\x1b[28m"
#define ANSI_ESC_NCROSSO   "\x1b[29m"
#define ANSI_ESC_BLACK     "\x1b[30m" // fg color
#define ANSI_ESC_RED       "\x1b[31m"
#define ANSI_ESC_GREEN     "\x1b[32m"
#define ANSI_ESC_YELLOW    "\x1b[33m"
#define ANSI_ESC_BLUE      "\x1b[34m"
#define ANSI_ESC_MAGENTA   "\x1b[35m"
#define ANSI_ESC_CYAN      "\x1b[36m"
#define ANSI_ESC_WHITE     "\x1b[37m" // fg color
#define ANSI_ESC_SET256FG  "\x1b[38m"
#define ANSI_ESC_DFTTXTC   "\x1b[39m"
#define ANSI_ESC_BLACKBG   "\x1b[40m" // bg color
#define ANSI_ESC_REDBG     "\x1b[41m"
#define ANSI_ESC_GREENBG   "\x1b[42m"
#define ANSI_ESC_YELLOWBG  "\x1b[43m"
#define ANSI_ESC_BLUEBG    "\x1b[44m"
#define ANSI_ESC_MAGENTABG "\x1b[45m"
#define ANSI_ESC_CYANBG    "\x1b[46m"
#define ANSI_ESC_WHITEBG   "\x1b[47m" // bg color
#define ANSI_ESC_SETX256BG "\x1b[48m"
#define ANSI_ESC_DFTBGC    "\x1b[49m"
#define ANSI_ESC_RESERVED2 "\x1b[50m"
#define ANSI_ESC_FRAMED    "\x1b[51m"
#define ANSI_ESC_ENCIRCLED "\x1b[52m"
#define ANSI_ESC_OVERLINED "\x1b[53m"
#define ANSI_ESC_NFRMNENC  "\x1b[54m"
#define ANSI_ESC_NOLINED   "\x1b[55m"
#define ANSI_ESC_RESERVED3 "\x1b[56m"
#define ANSI_ESC_RESERVED4 "\x1b[57m"
#define ANSI_ESC_RESERVED5 "\x1b[58m"
#define ANSI_ESC_RESERVED6 "\x1b[59m"
#define ANSI_ESC_IDEULRL   "\x1b[60m"
#define ANSI_ESC_IDEDBLURL "\x1b[61m"
#define ANSI_ESC_IDEOLLL   "\x1b[62m"
#define ANSI_ESC_IDEDBLLL  "\x1b[63m"
#define ANSI_ESC_IDESTRESS "\x1b[64m"

#endif
